version: 2
working_directory: ~/app1
jobs:
   build:
     docker:
       - image: circleci/node:6
       - image: circleci/python:3.4
     steps:
       - checkout
       - run: npm install 
       - run: npm run build
       - run: echo "hello world"
       - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            python get-pip.py --user
            pip install awscli --upgrade --user
            aws s3 sync ~/app1/build s3://staging-area1  --delete  