version: 2
working_directory: ~/app1
jobs:
   build:
     docker:
       - image: circleci/node:6
        
     steps:
       - checkout
       - run: npm install 
       - run: npm run build
       - run: echo "hello world"
       - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
            aws s3 sync ~/app1/build s3://staging-area1  --delete  