version: 2
working_directory: ~/app1
jobs:
   build:
     docker:
       - image: circleci/node:6
       - image: circleci/python:3.6
     steps:
       - checkout
       - run: npm install 
       - run: npm run build
       - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            pip install awscli
            aws s3 sync ~/app1/build s3://staging-area1  --delete  