version: 2
working_directory: ~/app1
jobs:
   build:
     docker:
       - image: circleci/node:6
        
     steps:
       - checkout
       - run: npm install react-scripts -g
       - run: npm run build
       - run: echo "hello world"
       