version: 2

jobs:
   build:
     docker:
       - image: circleci/node:6
    working_directory: ~/app1    
     steps:
       - checkout
       - run: npm run build
       - run: echo "hello world"
       