
version: 2
working_directory: ~/app1 
jobs:
  build-job:
    docker:
      - image: circleci/node:6
    steps:
       - checkout
       - run: npm install 
       - run: npm run build  
       
  deploy-job:
    docker:
      - image: circleci/node:6
    steps:
       - checkout
       - run: npm install 
       - run: npm run build 
       
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
