
version: 2
jobs:
  build-job:
    docker:
    image: circleci/node:6[
  working_directory: ~/app1 
    steps:
      - run:
            name: build process
            command: npm run build
            
  deploy-job:
    working_directory: ~/app1  
    steps:
    - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
            aws s3 sync ~/app1 s3://staging-area1  --delete
    

          
deploy:
    
    working_directory: /tmp/app1
    steps:
    - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
            aws s3 sync ~/app1 s3://staging-area1  --delete
    

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
