version: 2
working_directory: ~/app1
jobs:
   build:
     docker:
       - image: circleci/node:6
        
     steps:
       - checkout
       - run: npm install 
       - run: npm run build
       - run: echo "hello world"
       - run: aws s3 sync ~/app1/build s3://staging-area1  --delete 
           